title: "DELI Design Studio & Consulting"
description: "Architecture studio focused on residential, commercial, and interior design."
url: "https://deli.ba"
baseurl: ""

markdown: kramdown
permalink: /blog/:title/

collections:
  projects:
    output: true
    permalink: /portfolio/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

exclude:
  - README.md
